=== spryker/demoshop/config/Zed/oms/process.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="statemachine" type="statemachineType"/>
    <xs:complexType name="processType" mixed="true">
        <xs:sequence>
            <xs:element type="subprocessesType" name="subprocesses" minOccurs="0"/>
            <xs:element type="statesType" name="states" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>TODO exclude from invoice</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="transitionsType" name="transitions" minOccurs="0"/>
            <xs:element type="eventsType" name="events" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>TODO find merchant</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="main" use="optional"/>
        <xs:attribute type="xs:string" name="file" use="optional"/>
    </xs:complexType>
    <xs:complexType name="statesType">
        <xs:sequence>
            <xs:element type="stateType" name="state" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="transitionsType">
        <xs:sequence>
            <xs:element type="transitionType" name="transition" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="stateType" mixed="true">
        <xs:sequence>
            <xs:element name="flag" maxOccurs="unbounded" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="exclude from customer"/>
                        <xs:enumeration value="exclude from invoice"/>
                        <xs:enumeration value="ready for invoice"/>
                        <xs:enumeration value="waiting for export"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="display" use="optional"/>
        <xs:attribute type="xs:string" name="reserved" use="optional"/>
    </xs:complexType>
    <xs:complexType name="statemachineType" mixed="true">
        <xs:sequence>
            <xs:element type="processType" name="process" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="transitionType">
        <xs:sequence>
            <xs:element type="xs:string" name="source"/>
            <xs:element type="xs:string" name="target"/>
            <xs:element type="xs:string" name="event" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="happy" use="optional"/>
        <xs:attribute type="xs:string" name="condition" use="optional"/>
    </xs:complexType>
    <xs:complexType name="eventType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="timeout" use="optional"/>
                <xs:attribute type="xs:string" name="onEnter" use="optional"/>
                <xs:attribute type="xs:string" name="manual" use="optional"/>
                <xs:attribute type="xs:string" name="command" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="subprocessesType">
        <xs:sequence>
            <xs:element name="process" maxOccurs="unbounded" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="invoice creation"/>
                        <xs:enumeration value="fulfillment"/>
                        <xs:enumeration value="completion"/>
                        <xs:enumeration value="cancellation"/>
                        <xs:enumeration value="return shipment"/>
                        <xs:enumeration value="find merchant"/>
                        <xs:enumeration value="return debit note"/>
                        <xs:enumeration value="dunning process"/>
                        <xs:enumeration value="payone capture"/>
                        <xs:enumeration value="payone capture after fulfillment"/>
                        <xs:enumeration value="postal invoice delivery"/>
                        <xs:enumeration value="payone waiting for invoice payment"/>
                        <xs:enumeration value="manual trustability check"/>
                        <xs:enumeration value="delivery slip creation"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="eventsType">
        <xs:sequence>
            <xs:element type="eventType" name="event" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== spryker/demoshop/config/Zed/oms/SepaDirectDebit01.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="process.xsd">
    <process name="SepaDirectDebit01" main="true">

        <subprocesses>
            <process>adyen capture</process>
            <process>export afterbuy</process>
        </subprocesses>

        <states>
            <state name="new"/>
            <state name="payment request sent"/>
            <state name="payment request valid"/>
            <state name="payment request invalid"/>
            <state name="authorisation notification received"/>
            <state name="invalid"/>
            <state name="paid"/>
        </states>

        <transitions>

            <transition happy="true">
                <source>new</source>
                <target>payment request sent</target>
                <event>send payment request</event>
            </transition>

            <transition happy="true" condition="Adyen/IsAuthoriseTransactionSuccess">
                <source>payment request sent</source>
                <target>payment request valid</target>
                <event>adyen check payment request</event>
            </transition>

            <transition>
                <source>payment request sent</source>
                <target>payment request invalid</target>
                <event>adyen check payment request</event>
            </transition>

            <transition>
                <source>payment request invalid</source>
                <target>invalid</target>
                <event>invalidate order</event>
            </transition>

            <transition>
                <source>invalid</source>
                <target>invalid</target>
                <event>redeem voucher</event>
            </transition>

            <transition happy="true" condition="Adyen/IsAuthoriseNotificationSuccess">
                <source>payment request valid</source>
                <target>authorisation notification received</target>
            </transition>

            <transition happy="true" condition="Adyen/IsAuthoriseNotificationSuccess">
                <source>authorisation notification received</source>
                <target>paid</target>
                <event>adyen check authorisation notification</event>
            </transition>

            <transition>
                <source>authorisation notification received</source>
                <target>invalid</target>
                <event>adyen check authorisation notification</event>
            </transition>

            <!-- SUBPROCESS CONNECTIONS -->

            <transition>
                <source>paid</source>
                <target>init capture process</target>
                <event>init capture</event>
            </transition>

            <transition>
                <source>captured</source>
                <target>init export to afterbuy</target>
                <event>init afterbuy export</event>
            </transition>

        </transitions>

        <events>
            <event name="send payment request" onEnter="true" manual="true" command="Adyen/Authorise"/>
            <event name="check authorisation" onEnter="false" manual="true"/>
            <event name="adyen check authorisation notification" onEnter="true"/>
            <event name="adyen check payment request" onEnter="true" />
            <event name="invalidate order" onEnter="true"/>
            <event name="redeem voucher" onEnter="true" command="TODO/RedeemVoucher"/>

            <!-- SUBPROCESS CONNECTIONS -->
            <event name="init capture" onEnter="true"/>
            <event name="init afterbuy export" onEnter="true"/>
        </events>

    </process>


    <process name="adyen capture" file="subprocesses/Capture01.xml"/>
    <process name="export afterbuy" file="subprocesses/ExportAfterBuy01.xml"/>

</statemachine>

=== spryker/demoshop/config/Zed/oms/subprocesses/ExportAfterBuy01.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../process.xsd">

    <process name="export afterbuy">

        <states>
            <state name="init export to afterbuy"/>
            <state name="exported to afterbuy"/>
            <state name="clarify afterbuy export failed"/>
        </states>

        <transitions>

            <transition happy="true" condition="AfterbuyExporter/IsAfterbuyExportSuccessful">
                <source>init export to afterbuy</source>
                <target>exported to afterbuy</target>
                <event>export to afterbuy</event>
            </transition>

            <transition>
                <source>init export to afterbuy</source>
                <target>clarify afterbuy export failed</target>
                <event>export to afterbuy</event>
            </transition>

            <transition>
                <source>clarify afterbuy export failed</source>
                <target>init export to afterbuy</target>
                <event>retry export to afterbuy</event>
            </transition>

        </transitions>

        <events>
            <event name="export to afterbuy" manual="true" command="OrderExporter/ExportOrderItems"/>
            <event name="retry export to afterbuy" manual="true"/>
        </events>

    </process>

</statemachine>

=== spryker/demoshop/config/Zed/oms/subprocesses/ExportAfterbuy.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../process.xsd">
    <process name="exportAfterbuy">
        <states>
            <state name="init export"/>
            <state name="exported to afterbuy"/>
            <state name="clarify afterbuy export failed"/>
        </states>

        <transitions>
            <transition happy="true" condition="AfterbuyExporter/IsAfterbuyExportSuccessful">
                <source>init export</source>
                <target>exported to afterbuy</target>
                <event>export to afterbuy</event>
            </transition>

            <transition>
                <source>init export</source>
                <target>clarify afterbuy export failed</target>
                <event>export to afterbuy</event>
            </transition>
        </transitions>

        <events>
            <event name="export to afterbuy" manual="true" command="OrderExporter/ExportOrderItems"/>
        </events>
    </process>
</statemachine>

=== spryker/demoshop/config/Zed/oms/Prepayment01.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="process.xsd">
    <process name="Prepayment01" main="true">
        <subprocesses>
            <process>fulfillment</process>
            <process>completion</process>
            <process>return shipment</process>
            <process>cancellation</process>
        </subprocesses>
        <states>
            <state name="new" reserved="true"/>
            <state name="request to pay sent"/>
            <state name="payment received"/>
            <state name="clarify reminder"/>
            <state name="invalid" reserved="false"/>
            <state name="clarify under- or overpaid"/>
            <state name="paid">
                <flag>ready for invoice</flag>
            </state>
            <state name="invoice sent"/>
            <state name="invoice created"/>
        </states>
        <transitions>

            <transition>
                <source>new</source>
                <target>request to pay sent</target>
                <event>send payment request</event>
            </transition>

            <transition>
                <source>request to pay sent</source>
                <target>clarify reminder</target>
                <event>remind customer</event>
            </transition>

            <transition>
                <source>clarify reminder</source>
                <target>payment received</target>
                <event>receive payment</event>
            </transition>

            <transition>
                <source>request to pay sent</source>
                <target>payment received</target>
                <event>receive payment</event>
            </transition>

            <transition>
                <source>clarify under- or overpaid</source>
                <target>payment received</target>
                <event>receive payment</event>
            </transition>

            <transition>
                <source>clarify reminder</source>
                <target>invalid</target>
                <event>mark invalid</event>
            </transition>
            <transition>
                <source>payment received</source>
                <target>paid</target>
                <event>payment amount matches</event>
            </transition>
            <transition>
                <source>payment received</source>
                <target>clarify under- or overpaid</target>
                <event>resolve amount mismatch</event>
            </transition>

            <transition>
                <source>clarify under- or overpaid</source>
                <target>paid</target>
                <event>manually set paid</event>
            </transition>


            <transition>
                <source>paid</source>
                <target>invoice created</target>
                <event>create invoice</event>
            </transition>
            <transition>
                <source>invoice created</source>
                <target>invoice sent</target>
                <event>send invoice</event>
            </transition>

            <!-- Interprocess Transistions -->
            <!-- - - - - - - - - - - - - - -->
            <transition>
                <source>invoice sent</source>
                <target>fulfillment initiated</target>
            </transition>

            <transition>
                <source>fulfilled</source>
                <target>completed but returnable</target>
            </transition>

            <transition>
                <source>completed but returnable</source>
                <target>return shipment initiated</target>
                <event>initialize return</event>
            </transition>

            <transition>
                <source>return shipment initiated</source>
                <target>completed but returnable</target>
                <event>item not returned</event>
            </transition>
            <transition>
                <source>return arrived</source>
                <target>cancellation initiated</target>
                <event>refund desired</event>
            </transition>

            <transition>
                <source>return arrived</source>
                <target>fulfillment initiated</target>
                <event>new item requested</event>
            </transition>

            <transition>
                <source>clarify delivery failed</source>
                <target>cancellation initiated</target>
                <event>cancel delivery</event>
            </transition>

        </transitions>

        <events>
            <event name="send payment request" onEnter="true" manual="true" command="Oms/SendPaymentRequest"/>
            <event name="remind customer" timeout="14days"/>
            <event name="mark invalid" timeout="14days"/>
            <event name="receive payment" manual="true"/>
            <event name="check amount"/>
            <event name="payment amount matches" manual="true"/>
            <event name="resolve amount mismatch" manual="true"/>
            <event name="manually set paid" manual="true"/>
            <event name="create invoice" command="Oms/CreateInvoice" onEnter="true"/>
            <event name="send invoice" command="Oms/SendInvoice" onEnter="true"/>
            <event name="cancel delivery" manual="true"/>
            <event name="initialize return" manual="true"/>
            <event name="item not returned" timeout="14days"/>
            <event name="refund desired" manual="true"/>
            <event name="new item requested" manual="true"/>
        </events>


    </process>
    <process name="fulfillment" file="subprocesses/Fulfillment01.xml"/>
    <process name="completion" file="subprocesses/Completion01.xml"/>
    <process name="return shipment" file="subprocesses/ReturnShipment01.xml"/>
    <process name="cancellation" file="subprocesses/Cancellation01.xml"/>
</statemachine>

=== spryker/demoshop/config/Zed/oms/PayolutionSubProcesses/Shipment.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../process.xsd"
>
    <process name="Shipment">
        <states>
            <state name="ready for shipment"/>
            <state name="shipped"/>
        </states>

        <transitions>
            <transition happy="true">
                <source>ready for shipment</source>
                <target>shipped</target>
                <event>ship</event>
            </transition>
        </transitions>

        <events>
            <event name="ship" manual="true"/>
        </events>
    </process>
</statemachine>

=== spryker/demoshop/config/Zed/oms/Invoice01.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="process.xsd">

    <process name="Invoice01" main="true">
        <states>
            <state name="new"/>
            <state name="invoice created"/>
            <state name="invoice creation failed"/>
            <state name="invoice sent" />
            <state name="order exported" />
            <state name="order exporting failed"/>
            <state name="order shipped" />
            <state name="waiting for payment" />
            <state name="payment received" />
            <state name="reminder I sent" />
            <state name="reminder II sent" />
            <state name="dunning process started" />
            <state name="ready for return" />
            <state name="completed" />
        </states>

        <transitions>
            <transition condition="Oms/IsInvoiceCreated">
                <source>new</source>
                <target>invoice created</target>
                <event>create invoice</event>
            </transition>
            <transition>
                <source>new</source>
                <target>invoice creation failed</target>
                <event>create invoice</event>
            </transition>

            <transition>
                <source>invoice created</source>
                <target>invoice sent</target>
                <event>send invoice</event>
            </transition>

            <transition condition="Oms/IsOrderExported">
                <source>invoice sent</source>
                <target>order exported</target>
                <event>export order</event>
            </transition>
            <transition>
                <source>invoice sent</source>
                <target>order exporting failed</target>
                <event>export order</event>
            </transition>

            <transition>
                <source>order exported</source>
                <target>order shipped</target>
                <event>ship order</event>
            </transition>

            <transition>
                <source>order shipped</source>
                <target>waiting for payment</target>
                <event>waiting for payment</event>
            </transition>

            <transition>
                <source>waiting for payment</source>
                <target>reminder I sent</target>
                <event>send reminder</event>
            </transition>

            <transition>
                <source>waiting for payment</source>
                <target>payment received</target>
                <event>confirm payment</event>
            </transition>

            <transition>
                <source>reminder I sent</source>
                <target>reminder II sent</target>
                <event>send reminder</event>
            </transition>

            <transition>
                <source>reminder I sent</source>
                <target>payment received</target>
                <event>confirm payment</event>
            </transition>

            <transition>
                <source>reminder II sent</source>
                <target>dunning process started</target>
                <event>send reminder</event>
            </transition>

            <transition>
                <source>reminder II sent</source>
                <target>payment received</target>
                <event>confirm payment</event>
            </transition>

            <transition>
                <source>dunning process started</source>
                <target>payment received</target>
                <event>confirm payment</event>
            </transition>

            <transition>
                <source>payment received</source>
                <target>ready for return</target>
                <event>ready for return</event>
            </transition>

            <transition>
                <source>ready for return</source>
                <target>completed</target>
                <event>complete order</event>
            </transition>

        </transitions>

        <events>
            <event name="create invoice" command="Oms/CreateInvoice" onEnter="true" />
            <event name="send invoice" command="Oms/SendInvoice" onEnter="true" />
            <event name="export order" command="Oms/ExportOrder" onEnter="true" />
            <event name="ship order" manual="true" />
            <event name="waiting for payment" onEnter="true" />
            <event name="send reminder" timeout="1hour" />
            <event name="confirm payment" manual="true" />
            <event name="ready for return"  onEnter="true" />
            <event name="complete order" timeout="14days" />
        </events>
    </process>

</statemachine>

=== spryker/demoshop/config/Zed/oms/prepayment01.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="process.xsd">

    <process name="Prepayment01" main="true">
        <states>
            <state name="new" reserved="true"/>
            <state name="invoice sent" />
            <state name="payment received"/>
            <state name="clarify reminder"/>
            <state name="invalid" reserved="false"/>
            <state name="clarify under- or overpaid" />
            <state name="paid" />
        </states>
        <transitions>

            <transition>
                <source>new</source>
                <target>invoice sent</target>
                <event>send invoice</event>
            </transition>

            <transition>
                <source>invoice sent</source>
                <target>clarify reminder</target>
                <event>remind customer</event>
            </transition>

            <transition>
                <source>clarify reminder</source>
                <target>payment received</target>
                <event>receive payment</event>
            </transition>

            <transition>
                <source>invoice sent</source>
                <target>payment received</target>
                <event>receive payment</event>
            </transition>

            <transition>
                <source>clarify under- or overpaid</source>
                <target>payment received</target>
                <event>receive payment</event>
            </transition>

            <transition>
                <source>clarify reminder</source>
                <target>invalid</target>
                <event>mark invalid</event>
            </transition>
            <transition condition="Prepayment/AmountMatches">
                <source>payment received</source>
                <target>paid</target>
                <event>check amount</event>
            </transition>
            <transition>
                <source>payment received</source>
                <target>clarify under- or overpaid</target>
                <event>check amount</event>
            </transition>
            
            <transition>
                <source>clarify under- or overpaid</source>
                <target>paid</target>
                <event>manually set paid</event>
            </transition>
        </transitions>

        <events>
            <event name="send invoice" onEnter="true" />
            <event name="remind customer" timeout="14days" onEnter="true" />
            <event name="mark invalid" timeout="14days" />
            <event name="receive payment" />
            <event name="check amount" />
            <event name="amount matched" />
            <event name="resolve amount mismatch"/>
            <event name="manually set paid" manual="true" />
        </events>
    </process>

</statemachine>

=== spryker/demoshop/config/Zed/oms/subprocesses/Capture01.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../process.xsd">

    <process name="adyen capture">

        <states>
            <state name="init capture process"/>
            <state name="capture request sent"/>
            <state name="capture notification received"/>
            <state name="capture failed"/>
            <state name="captured"/>
        </states>

        <transitions>

            <transition happy="true">
                <source>init capture process</source>
                <target>capture request sent</target>
                <event>send capture request</event>
            </transition>

            <transition happy="true" condition="Adyen/HasCaptureNotificationReceived">
                <source>capture request sent</source>
                <target>capture notification received</target>
            </transition>

            <transition happy="true" condition="Adyen/IsCaptureNotificationSuccess">
                <source>capture notification received</source>
                <target>captured</target>
                <event>check capture notification</event>
            </transition>

            <transition>
                <source>capture notification received</source>
                <target>capture failed</target>
                <event>check capture notification</event>
            </transition>

            <transition>
                <source>capture failed</source>
                <target>init capture process</target>
                <event>retry capture</event>
            </transition>


        </transitions>

        <events>
            <event name="send capture request" command="Adyen/Capture" onEnter="true"/>
            <event name="check capture result"/>
            <event name="retry capture" manual="true"/>
            <event name="captured notification received"/>
            <event name="capture failed notification received"/>
            <event name="check capture notification" manual="true" onEnter="true"/>
        </events>

    </process>

</statemachine>
