=== spryker/demoshop/config/Zed/oms/process.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="statemachine" type="statemachineType"/>
    <xs:complexType name="processType" mixed="true">
        <xs:sequence>
            <xs:element type="subprocessesType" name="subprocesses" minOccurs="0"/>
            <xs:element type="statesType" name="states" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>TODO exclude from invoice</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="transitionsType" name="transitions" minOccurs="0"/>
            <xs:element type="eventsType" name="events" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>TODO find merchant</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="main" use="optional"/>
        <xs:attribute type="xs:string" name="file" use="optional"/>
    </xs:complexType>
    <xs:complexType name="statesType">
        <xs:sequence>
            <xs:element type="stateType" name="state" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="transitionsType">
        <xs:sequence>
            <xs:element type="transitionType" name="transition" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="stateType" mixed="true">
        <xs:sequence>
            <xs:element name="flag" maxOccurs="unbounded" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="exclude from customer"/>
                        <xs:enumeration value="exclude from invoice"/>
                        <xs:enumeration value="ready for invoice"/>
                        <xs:enumeration value="waiting for export"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="display" use="optional"/>
        <xs:attribute type="xs:string" name="reserved" use="optional"/>
    </xs:complexType>
    <xs:complexType name="statemachineType" mixed="true">
        <xs:sequence>
            <xs:element type="processType" name="process" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="transitionType">
        <xs:sequence>
            <xs:element type="xs:string" name="source"/>
            <xs:element type="xs:string" name="target"/>
            <xs:element type="xs:string" name="event" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="happy" use="optional"/>
        <xs:attribute type="xs:string" name="condition" use="optional"/>
    </xs:complexType>
    <xs:complexType name="eventType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="timeout" use="optional"/>
                <xs:attribute type="xs:string" name="onEnter" use="optional"/>
                <xs:attribute type="xs:string" name="manual" use="optional"/>
                <xs:attribute type="xs:string" name="command" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="subprocessesType">
        <xs:sequence>
            <xs:element name="process" maxOccurs="unbounded" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="invoice creation"/>
                        <xs:enumeration value="fulfillment"/>
                        <xs:enumeration value="completion"/>
                        <xs:enumeration value="cancellation"/>
                        <xs:enumeration value="return shipment"/>
                        <xs:enumeration value="find merchant"/>
                        <xs:enumeration value="return debit note"/>
                        <xs:enumeration value="dunning process"/>
                        <xs:enumeration value="payone capture"/>
                        <xs:enumeration value="payone capture after fulfillment"/>
                        <xs:enumeration value="postal invoice delivery"/>
                        <xs:enumeration value="payone waiting for invoice payment"/>
                        <xs:enumeration value="manual trustability check"/>
                        <xs:enumeration value="delivery slip creation"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="eventsType">
        <xs:sequence>
            <xs:element type="eventType" name="event" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== spryker/demoshop/config/Zed/oms/subprocesses/ReturnShipment01.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../process.xsd">
    <process name="return shipment">
        <states>
            <state name="return shipment initiated"/>
            <state name="return arrived"/>
        </states>
        
        <transitions>
            <transition>
                <source>return shipment initiated</source>
                <target>return arrived</target>
            </transition>
        </transitions>
    </process>
</statemachine>

=== spryker/demoshop/config/Zed/oms/PPrepayment01.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="process.xsd">
    <process name="Prepayment01" main="true">
        <subprocesses>
            <process>fulfillment</process>
            <process>completion</process>
            <process>return shipment</process>
            <process>cancellation</process>
        </subprocesses>
        <states>
            <state name="new" reserved="true"/>
            <state name="request to pay sent" />
            <state name="payment received"/>
            <state name="clarify reminder"/>
            <state name="invalid" reserved="false"/>
            <state name="clarify under- or overpaid" />
            <state name="paid" />
            <state name="invoice sent" />
            <state name="invoice created" />
        </states>
        <transitions>

            <transition>
                <source>new</source>
                <target>request to pay sent</target>
                <event>send payment request</event>
            </transition>

            <transition>
                <source>request to pay sent</source>
                <target>clarify reminder</target>
                <event>remind customer</event>
            </transition>

            <transition>
                <source>clarify reminder</source>
                <target>payment received</target>
                <event>receive payment</event>
            </transition>

            <transition>
                <source>request to pay sent</source>
                <target>payment received</target>
                <event>receive payment</event>
            </transition>

            <transition>
                <source>clarify under- or overpaid</source>
                <target>payment received</target>
                <event>receive payment</event>
            </transition>

            <transition>
                <source>clarify reminder</source>
                <target>invalid</target>
                <event>mark invalid</event>
            </transition>
            <transition condition="Prepayment/AmountMatches">
                <source>payment received</source>
                <target>paid</target>
                <event>check amount</event>
            </transition>
            <transition>
                <source>payment received</source>
                <target>clarify under- or overpaid</target>
                <event>check amount</event>
            </transition>
            
            <transition>
                <source>clarify under- or overpaid</source>
                <target>paid</target>
                <event>manually set paid</event>
            </transition>


            <transition>
                <source>paid</source>
                <target>invoice created</target>
                <event>create invoice</event>
            </transition>
            <transition>
                <source>invoice created</source>
                <target>invoice sent</target>
                <event>send invoice</event>
            </transition>

            <!-- Interprocess Transistions -->
            <!-- - - - - - - - - - - - - - -->
            <transition>
                <source>invoice sent</source>
                <target>fulfillment initiated</target>
            </transition>
            
            <transition>
                <source>fulfilled</source>
                <target>completed but returnable</target>
            </transition>
            
            <transition>
                <source>completed but returnable</source>
                <target>return shipment initiated</target>
            </transition>
            
            <transition>
                <source>return arrived</source>
                <target>cancellation initiated</target>
            </transition>
            
            <transition>
                <source>return arrived</source>
                <target>fulfillment initiated</target>
            </transition>

            <transition>
                <source>return shipment initiated</source>
                <target>completed but returnable</target>
            </transition>
            
            
        </transitions>

        <events>
            <event name="send payment request" onEnter="true" />
            <event name="remind customer" timeout="14days" onEnter="true" />
            <event name="mark invalid" timeout="14days" />
            <event name="receive payment" />
            <event name="check amount" />
            <event name="amount matched" />
            <event name="resolve amount mismatch"/>
            <event name="manually set paid" manual="true" />
            <event name="create invoice" />
            <event name="send invoice" />
        </events>



    </process>
    <process name="fulfillment" file="subprocesses/Fulfillment01.xml"/>
    <process name="completion" file="subprocesses/Completion01.xml"/>
    <process name="return shipment" file="subprocesses/ReturnShipment01.xml"/>
    <process name="cancellation" file="subprocesses/Cancellation01.xml" />
</statemachine>

=== spryker/demoshop/config/Zed/oms/subprocesses/Cancellation01.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../process.xsd">
    <process name="cancellation">
        <states>
            <state name="init cancellation"/>
            <state name="clarify refundable voucher code"/>
            <state name="clarify refund money"/>
            <state name="refunded"/>
        </states>

        <transitions>
            <transition>
                <source>init cancellation</source>
                <target>clarify refundable voucher code</target>
                <event>start refund checks</event>
            </transition>
            <transition>
                <source>clarify refundable voucher code</source>
                <target>clarify refund money</target>
                <event>voucher checked</event>
            </transition>
            <transition>
                <source>clarify refund money</source>
                <target>refunded</target>
                <event>refund done</event>
            </transition>
        </transitions>

        <events>
            <event name="start refund checks" manual="true"/>
            <event name="voucher checked" manual="true"/>
            <event name="refund done" manual="true"/>
        </events>
    </process>
</statemachine>

=== spryker/demoshop/config/Zed/oms/BraintreePayPal01.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="process.xsd"
>
    <process name="BraintreePayPal01" main="true">
        <subprocesses>
            <process>Capture</process>
            <process>Shipment</process>
            <process>Refund</process>
            <process>Closing</process>
        </subprocesses>

        <states>
            <state name="new" reserved="true"/>
            <state name="authorized" reserved="true"/>
            <state name="invalid"/>
            <state name="revert succeeded"/>
        </states>

        <transitions>
            <transition happy="true" condition="Braintree/IsAuthorizationApproved">
                <source>new</source>
                <target>authorized</target>
                <event>finalize authorization process</event>
            </transition>

            <transition>
                <source>new</source>
                <target>invalid</target>
                <event>finalize authorization process</event>
            </transition>

            <transition condition="Braintree/IsReversalApproved">
                <source>authorized</source>
                <target>revert succeeded</target>
                <event>revert payment</event>
            </transition>

            <transition happy="true">
                <source>authorized</source>
                <target>ready for capture</target>
                <event>start capture process</event>
            </transition>

            <transition happy="true">
                <source>capture succeeded</source>
                <target>ready for shipment</target>
                <event>start shipment process</event>
            </transition>

            <transition>
                <source>capture succeeded</source>
                <target>ready for refund</target>
                <event>start refund process</event>
            </transition>

            <transition happy="true">
                <source>shipped</source>
                <target>ready for closing</target>
                <event>start closing process with timeout</event>
            </transition>

            <transition>
                <source>refund succeeded</source>
                <target>ready for closing</target>
                <event>start closing process</event>
            </transition>
        </transitions>

        <events>
            <event name="finalize authorization process" onEnter="true" command="Braintree/Authorize"/>
            <event name="revert payment" manual="true" command="Braintree/Revert"/>
            <event name="start shipment process" manual="true"/>
            <event name="start capture process" onEnter="true"/>
            <event name="start refund process" manual="true"/>
            <event name="start closing process with timeout" timeout="14days"/>
            <event name="start closing process" onEnter="true"/>
        </events>
    </process>

    <process name="Shipment" file="BraintreeSubProcesses/Shipment.xml"/>
    <process name="Capture" file="BraintreeSubProcesses/Capture.xml"/>
    <process name="Refund" file="BraintreeSubProcesses/Refund.xml"/>
    <process name="Closing" file="BraintreeSubProcesses/Closing.xml"/>
</statemachine>

=== spryker/demoshop/config/Zed/oms/PrePayment01.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="process.xsd">
    <process name="PrePayment01" main="true">

        <subprocesses>
            <process>export afterbuy</process>
        </subprocesses>

        <states>
            <state name="new"/>
            <state name="redirected"/>
            <state name="authorise notification received"/>
            <state name="invalid"/>
            <state name="waiting for authorise notification"/>
            <state name="clarify authorise notification not received"/>
            <state name="redirect payment timeout"/>
            <state name="customer cancelled payment" />
            <state name="cancelled payment after timeout" />
            <state name="ready to send confirmation mail" />
            <state name="payment error" />
            <state name="paid"/>
        </states>

        <transitions>

            <transition happy="true">
                <source>new</source>
                <target>redirected</target>
                <event>create redirect request</event>
            </transition>

            <transition condition="Adyen/HasPendingNotificationReceived" happy="true">
                <source>redirected</source>
                <target>waiting for authorise notification</target>
            </transition>

            <transition>
                <source>waiting for authorise notification</source>
                <target>waiting for authorise notification</target>
                <event>send order received mail</event>
            </transition>

            <transition happy="true" condition="Adyen/IsAuthoriseNotificationSuccess" >
                <source>authorise notification received</source>
                <target>ready to send confirmation mail</target>
                <event>adyen check authorise notification</event>
            </transition>

            <transition happy="true">
                <source>ready to send confirmation mail</source>
                <target>paid</target>
                <event>send order confirmation mail</event>
            </transition>

            <transition condition="Adyen/HasAuthoriseNotificationReceived" happy="true">
                <source>waiting for authorise notification</source>
                <target>authorise notification received</target>
            </transition>

            <transition>
                <source>waiting for authorise notification</source>
                <target>clarify authorise notification not received</target>
                <event>timeout missing authorise notification</event>
            </transition>

            <transition condition="Adyen/HasAuthoriseNotificationReceived">
                <source>clarify authorise notification not received</source>
                <target>authorise notification received</target>
            </transition>


            <transition>
                <source>authorise notification received</source>
                <target>invalid</target>
                <event>adyen check authorise notification</event>
            </transition>

            <transition>
                <source>redirected</source>
                <target>redirect payment timeout</target>
                <event>adyen timeout pending notification not received</event>
            </transition>

            <transition condition="Adyen/HasPendingNotificationReceived">
                <source>redirect payment timeout</source>
                <target>waiting for authorise notification</target>
            </transition>

            <transition>
                <source>redirect payment timeout</source>
                <target>cancelled payment after timeout</target>
                <event>adyen timeout payment cancellation</event>
            </transition>

            <transition>
                <source>cancelled payment after timeout</source>
                <target>invalid</target>
                <event>adyen invalidate timeout cancelled payment</event>
            </transition>

            <transition>
                <source>redirected</source>
                <target>customer cancelled payment</target>
                <event>adyen redirect payment cancelled</event>
            </transition>

            <transition>
                <source>customer cancelled payment</source>
                <target>invalid</target>
                <event>adyen invalidate cancelled payment</event>
            </transition>

            <transition>
                <source>redirected</source>
                <target>payment error</target>
                <event>adyen redirect payment error</event>
            </transition>

            <transition>
                <source>payment error</source>
                <target>invalid</target>
                <event>adyen invalidate error payment</event>
            </transition>

            <!-- SUBPROCESS CONNECTIONS -->

            <transition>
                <source>paid</source>
                <target>init export to afterbuy</target>
            </transition>

        </transitions>

        <events>
            <event name="create redirect request" onEnter="true" manual="true" command="Adyen/Authorise"/>
            <event name="check authorise" onEnter="false" manual="true"/>
            <event name="adyen authorise notification received" manual="true" onEnter="true"/>
            <event name="adyen check authorise notification" manual="true" onEnter="true"/>
            <event name="adyen check pending notification" onEnter="true"/>
            <event name="adyen timeout pending notification not received" timeout="1hour"/>
            <event name="adyen timeout invalidate redirect payment" timeout="1week"/>
            <event name="adyen redirect payment cancelled"/>
            <event name="adyen redirect payment error"/>
            <event name="adyen invalidate cancelled payment" onEnter="true" />
            <event name="adyen invalidate timeout cancelled payment" onEnter="true" />
            <event name="adyen invalidate error payment" onEnter="true" />
            <event name="adyen timeout payment cancellation" command="Adyen/Cancel" timeout="2days"/>
            <event name="send order confirmation mail" onEnter="true" command="OmsMailQueueConnector/OrderConfirmationMail"/>
            <event name="send order received mail" onEnter="true" command="TODO/DUMMY/ORDER-RECEIVED-MAIL"/>
            <event name="timeout missing authorise notification" timeout="1week"/>
        </events>

    </process>

    <process name="export afterbuy" file="subprocesses/ExportAfterBuy01.xml"/>

</statemachine>

=== spryker/demoshop/config/Zed/oms/subprocesses/Fulfillment01.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../process.xsd">
    <process name="fulfillment">
        <states>
            <state name="fulfillment initiated"/>
            <state name="ready for export"/>
            <state name="exported"/>
            <state name="shipped"/>
            <state name="fulfilled"/>
            <state name="clarify delivery failed"/>
        </states>
        <transitions>
            <transition>
                <source>fulfillment initiated</source>
                <target>ready for export</target>
            </transition>
            <transition>
                <source>ready for export</source>
                <target>exported</target>
                <event>start order export</event>
            </transition>
            <transition>
                <source>exported</source>
                <target>shipped</target>
                <event>has been shipped</event>
            </transition>
            <transition>
                <source>shipped</source>
                <target>fulfilled</target>
                <event>delivered successfully</event>
            </transition>
            <transition>
                <source>shipped</source>
                <target>clarify delivery failed</target>
                <event>delivery failed</event>
            </transition>
            <transition>
                <source>clarify delivery failed</source>
                <target>shipped</target>
                <event>retry delivery</event>
            </transition>
            <transition>
                <source>fulfilled</source>
                <target>clarify delivery failed</target>
                <event>delivery failed</event>
            </transition>
            <transition>
                <source>clarify delivery failed</source>
                <target>fulfilled</target>
                <event>was fulfilled</event>
            </transition>
            <transition>
                <source>clarify delivery failed</source>
                <target>fulfillment initiated</target>
                <event>item was lost</event>
            </transition>
        </transitions>

        <events>
            <event name="start order export" manual="true"/>
            <event name="has been shipped" manual="true"/>
            <event name="delivery failed" manual="true"/>
            <event name="retry delivery" manual="true"/>
            <event name="was fulfilled" manual="true"/>
            <event name="delivered successfully" timeout="1day" manual="true"/>
            <event name="item was lost" manual="true"/>
        </events>
    </process>
</statemachine>

=== spryker/demoshop/config/Zed/oms/CheckoutTest01.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="process.xsd">

    <process name="CheckoutTest01" main="true">
        <states>
            <state name="new" reserved="true"/>
            <state name="nopayment"/>
            <state name="ship"/>
            <state name="cronjob1"/>
        </states>

        <transitions>
            <transition happy="true">
                <source>new</source>
                <target>nopayment</target>
                <event>nopayment</event>
            </transition>
            <transition happy="true">
                <source>nopayment</source>
                <target>ship</target>
                <event>ship</event>
            </transition>
            <transition happy="true">
                <source>ship</source>
                <target>cronjob1</target>
            </transition>
        </transitions>

        <events>
            <event name="nopayment" onEnter="true" />
            <event name="ship" onEnter="true" />
        </events>
    </process>

</statemachine>
