=== spryker/demoshop/config/Zed/oms/process.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="statemachine" type="statemachineType"/>
    <xs:complexType name="processType" mixed="true">
        <xs:sequence>
            <xs:element type="subprocessesType" name="subprocesses" minOccurs="0"/>
            <xs:element type="statesType" name="states" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>TODO exclude from invoice</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="transitionsType" name="transitions" minOccurs="0"/>
            <xs:element type="eventsType" name="events" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>TODO find merchant</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="main" use="optional"/>
        <xs:attribute type="xs:string" name="file" use="optional"/>
    </xs:complexType>
    <xs:complexType name="statesType">
        <xs:sequence>
            <xs:element type="stateType" name="state" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="transitionsType">
        <xs:sequence>
            <xs:element type="transitionType" name="transition" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="stateType" mixed="true">
        <xs:sequence>
            <xs:element name="flag" maxOccurs="unbounded" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="exclude from customer"/>
                        <xs:enumeration value="exclude from invoice"/>
                        <xs:enumeration value="ready for invoice"/>
                        <xs:enumeration value="waiting for export"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="display" use="optional"/>
        <xs:attribute type="xs:string" name="reserved" use="optional"/>
    </xs:complexType>
    <xs:complexType name="statemachineType" mixed="true">
        <xs:sequence>
            <xs:element type="processType" name="process" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="transitionType">
        <xs:sequence>
            <xs:element type="xs:string" name="source"/>
            <xs:element type="xs:string" name="target"/>
            <xs:element type="xs:string" name="event" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="happy" use="optional"/>
        <xs:attribute type="xs:string" name="condition" use="optional"/>
    </xs:complexType>
    <xs:complexType name="eventType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="timeout" use="optional"/>
                <xs:attribute type="xs:string" name="onEnter" use="optional"/>
                <xs:attribute type="xs:string" name="manual" use="optional"/>
                <xs:attribute type="xs:string" name="command" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="subprocessesType">
        <xs:sequence>
            <xs:element name="process" maxOccurs="unbounded" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="invoice creation"/>
                        <xs:enumeration value="fulfillment"/>
                        <xs:enumeration value="completion"/>
                        <xs:enumeration value="cancellation"/>
                        <xs:enumeration value="return shipment"/>
                        <xs:enumeration value="find merchant"/>
                        <xs:enumeration value="return debit note"/>
                        <xs:enumeration value="dunning process"/>
                        <xs:enumeration value="payone capture"/>
                        <xs:enumeration value="payone capture after fulfillment"/>
                        <xs:enumeration value="postal invoice delivery"/>
                        <xs:enumeration value="payone waiting for invoice payment"/>
                        <xs:enumeration value="manual trustability check"/>
                        <xs:enumeration value="delivery slip creation"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="eventsType">
        <xs:sequence>
            <xs:element type="eventType" name="event" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== spryker/demoshop/config/Zed/oms/CreditCard01.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="process.xsd">
    <process name="CreditCard01" main="true">

        <subprocesses>
            <process>adyen capture</process>
            <process>export afterbuy</process>
        </subprocesses>

        <states>
            <state name="new"/>
            <state name="authorise request sent"/>
            <state name="authorise request success"/>
            <state name="authorise notification received"/>
            <state name="ready to send confirmation mail"/>
            <state name="invalid"/>
            <state name="paid"/>
        </states>

        <transitions>

            <transition happy="true">
                <source>new</source>
                <target>authorise request sent</target>
                <event>send authorise request</event>
            </transition>

            <transition happy="true" condition="Adyen/IsAuthoriseTransactionSuccess">
                <source>authorise request sent</source>
                <target>authorise request success</target>
                <event>adyen check authorise request</event>
            </transition>

            <transition>
                <source>authorise request sent</source>
                <target>invalid</target>
                <event>adyen check authorise request</event>
            </transition>

            <transition happy="true" condition="Adyen/IsAuthoriseNotificationSuccess">
                <source>authorise request success</source>
                <target>authorise notification received</target>
            </transition>

            <transition happy="true" condition="Adyen/IsAuthoriseNotificationSuccess">
                <source>authorise notification received</source>
                <target>ready to send confirmation mail</target>
                <event>adyen check authorise notification</event>
            </transition>

            <transition happy="true">
                <source>ready to send confirmation mail</source>
                <target>paid</target>
                <event>send order confirmation mail</event>
            </transition>

            <transition>
                <source>authorise notification received</source>
                <target>invalid</target>
                <event>adyen check authorise notification</event>
            </transition>

            <!-- SUBPROCESS CONNECTIONS -->

            <transition>
                <source>paid</source>
                <target>init capture process</target>
                <event>init capture</event>
            </transition>

            <transition>
                <source>captured</source>
                <target>init export to afterbuy</target>
                <event>init afterbuy export</event>
            </transition>

        </transitions>

        <events>
            <event name="send authorise request" onEnter="true" manual="true" command="Adyen/AuthoriseCreditCard"/>
            <event name="check authorise" onEnter="false" manual="true"/>
            <event name="adyen check authorise notification" onEnter="true"/>
            <event name="adyen check authorise request" onEnter="true" />
            <event name="send order confirmation mail" onEnter="true" command="TODO/DUMMY/DummySendOrderConfirmationMail"/>

            <!-- SUBPROCESS CONNECTIONS -->
            <event name="init capture" onEnter="true"/>
            <event name="init afterbuy export" onEnter="true"/>
        </events>

    </process>


    <process name="adyen capture" file="subprocesses/Capture01.xml"/>
    <process name="export afterbuy" file="subprocesses/ExportAfterBuy01.xml"/>


</statemachine>

=== spryker/demoshop/config/Zed/oms/PayoneCreditCardAuthorize01.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="process.xsd">

    <process name="PayoneCreditCardAuthorize" main="true">
        <states>
            <state name="ready for authorize" reserved="true"/>
            <state name="waiting for 3d-secure response"/>
            <state name="apointed"/>
            <state name="error"/>
            <state name="invalid"/>
            <state name="approved"/>
        </states>

        <transitions>
            <transition happy="true">
                <source>ready for authorize</source>
                <target>nopayment</target>
                <event>nopayment</event>
            </transition>
            <transition happy="true" condition="Nopayment/IsPaid">
                <source>nopayment</source>
                <target>ship</target>
            </transition>
            <transition>
                <source>nopayment</source>
                <target>cancel</target>
                <event>cancel</event>
            </transition>

            <transition>
                <source>cancel</source>
                <target>xxx</target>
                <event>dodo</event>
            </transition>
        </transitions>

        <events>
            <event name="nopayment" onEnter="true" command="Nopayment/SetAsPaid" manual="true"/>
            <event name="cancel" timeout="1min" manual="true"/>
            <event name="dodo"/>
        </events>
    </process>

</statemachine>

=== spryker/demoshop/config/Zed/oms/PayPal01.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="process.xsd">
    <process name="PayPal01" main="true">

        <subprocesses>
            <process>adyen capture</process>
            <process>export afterbuy</process>
        </subprocesses>

        <states>
            <state name="new"/>
            <state name="redirected"/>
            <state name="authorisation notification received"/>
            <state name="invalid"/>
            <state name="clarify redirect payment timeout"/>
            <state name="customer cancelled payment" />
            <state name="payment error" />
            <state name="paid"/>
        </states>

        <transitions>

            <transition happy="true">
                <source>new</source>
                <target>redirected</target>
                <event>send payment request</event>
            </transition>

            <transition>
                <source>invalid</source>
                <target>invalid</target>
                <event>redeem voucher for invalid order</event>
            </transition>

            <transition condition="Adyen/HasAuthoriseNotificationReceived" happy="true">
                <source>redirected</source>
                <target>authorisation notification received</target>
            </transition>

            <transition happy="true" condition="Adyen/IsAuthoriseNotificationSuccess" >
                <source>authorisation notification received</source>
                <target>paid</target>
                <event>adyen check authorisation notification</event>
            </transition>

            <transition>
                <source>authorisation notification received</source>
                <target>invalid</target>
                <event>adyen check authorisation notification</event>
            </transition>

            <transition>
                <source>redirected</source>
                <target>clarify redirect payment timeout</target>
                <event>adyen timeout authorisation notification not received</event>
            </transition>

            <transition>
                <source>clarify redirect payment timeout</source>
                <target>clarify redirect payment timeout</target>
                <event>redeem voucher for timed out order</event>
            </transition>

            <transition>
                <source>clarify redirect payment timeout</source>
                <target>invalid</target>
                <event>adyen timeout invalidate redirect payment</event>
            </transition>

            <transition>
                <source>redirected</source>
                <target>customer cancelled payment</target>
                <event>adyen redirect payment cancelled</event>
            </transition>

            <transition>
                <source>customer cancelled payment</source>
                <target>invalid</target>
                <event>adyen invalidate cancelled payment</event>
            </transition>

            <transition>
                <source>redirected</source>
                <target>payment error</target>
                <event>adyen redirect payment error</event>
            </transition>

            <transition>
                <source>payment error</source>
                <target>invalid</target>
                <event>adyen invalidate error payment</event>
            </transition>

            <!-- SUBPROCESS CONNECTIONS -->

            <transition>
                <source>paid</source>
                <target>init capture process</target>
                <event>init capture</event>
            </transition>

            <transition>
                <source>captured</source>
                <target>init export to afterbuy</target>
                <event>init afterbuy export</event>
            </transition>

        </transitions>

        <events>
            <event name="send payment request" onEnter="true" manual="true" command="Adyen/Authorise"/>
            <event name="check authorisation" onEnter="false" manual="true"/>
            <event name="redeem voucher for invalid order" onEnter="true" command="TODO/RedeemVoucher"/>
            <event name="redeem voucher for timed out order" onEnter="true" command="TODO/RedeemVoucher"/>
            <event name="adyen authorisation notification received" manual="true" onEnter="true"/>
            <event name="adyen check authorisation notification" manual="true" onEnter="true"/>
            <event name="adyen timeout authorisation notification not received" timeout="1hour"/>
            <event name="adyen timeout invalidate redirect payment" timeout="1week"/>;
            <event name="adyen redirect payment cancelled" command="Nofification/MailToDavid1"/>
            <event name="adyen redirect payment error" command="Nofification/MailToDavid2"/>
            <event name="adyen invalidate cancelled payment" onEnter="true" />;
            <event name="adyen invalidate error payment" onEnter="true" />;

            <!-- SUBPROCESS CONNECTIONS -->
            <event name="init capture" onEnter="true"/>
            <event name="init afterbuy export" onEnter="true"/>
        </events>

    </process>

    <process name="adyen capture" file="subprocesses/Capture01.xml"/>
    <process name="export afterbuy" file="subprocesses/ExportAfterBuy01.xml"/>

</statemachine>

=== spryker/demoshop/config/Zed/oms/subprocesses/Completion01.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../process.xsd">
    <process name="completion">
        <states>
            <state name="completed but returnable"/>
            <state name="completed success"/>
        </states>
        
        <transitions>
            <transition>
                <source>completed but returnable</source>
                <target>completed success</target>
            </transition>
        </transitions>
    </process>
</statemachine>

=== spryker/demoshop/config/Zed/oms/SofortUeberweisung01.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="process.xsd">
    <process name="SofortUeberweisung01" main="true">

        <subprocesses>
            <process>adyen capture</process>
            <process>export afterbuy</process>
        </subprocesses>

        <states>
            <state name="new" reserved="true"/>
            <state name="redirected"/>
            <state name="authorisation notification received"/>
            <state name="invalid" reserved="false"/>
            <state name="paid"/>
        </states>
        <transitions>

            <transition happy="true">
                <source>new</source>
                <target>redirected</target>
                <event>send payment request</event>
            </transition>

            <transition>
                <source>invalid</source>
                <target>invalid</target>
                <event>redeem voucher</event>
            </transition>

            <transition condition="Adyen/HasAuthoriseNotificationReceived" happy="true">
                <source>redirected</source>
                <target>authorisation notification received</target>
            </transition>

            <transition happy="true" condition="Adyen/IsAuthoriseNotificationSuccess" >
                <source>authorisation notification received</source>
                <target>paid</target>
                <event>check authorisation notification</event>
            </transition>

            <transition>
                <source>authorisation notification received</source>
                <target>invalid</target>
                <event>check authorisation notification</event>
            </transition>

            <transition>
                <source>redirected</source>
                <target>invalid</target>
                <event>adyen authorisation notification not received</event>
            </transition>

            <transition>
                <source>redirected</source>
                <target>invalid</target>
                <event>customer cancelled payment</event>
            </transition>

            <transition>
                <source>redirected</source>
                <target>invalid</target>
                <event>payment return with error</event>
            </transition>

            <!-- SUBPROCESS CONNECTIONS -->

            <transition>
                <source>paid</source>
                <target>init capture process</target>
                <event>init capture</event>
            </transition>

            <transition>
                <source>captured</source>
                <target>init export to afterbuy</target>
                <event>init afterbuy export</event>
            </transition>

        </transitions>

        <events>
            <event name="send payment request" onEnter="true" manual="true" command="Adyen/Authorise"/>
            <event name="check authorisation" onEnter="false" manual="true"/>
            <event name="redeem voucher" onEnter="true"/><!--  command="TODO/RedeemVoucher" -->
            <event name="adyen authorisation notification received" manual="true" onEnter="true"/>
            <event name="check authorisation notification" manual="true" onEnter="true"/>
            <event name="adyen authorisation notification not received" timeout="1hour"/>
            <event name="customer cancelled payment" />
            <event name="payment return with error" />

            <!-- SUBPROCESS CONNECTIONS -->
            <event name="init capture" onEnter="true"/>
            <event name="init afterbuy export" onEnter="true"/>
        </events>

    </process>

    <process name="adyen capture" file="subprocesses/Capture01.xml"/>
    <process name="export afterbuy" file="subprocesses/ExportAfterBuy01.xml"/>

</statemachine>

=== spryker/demoshop/config/Zed/oms/BraintreeSubProcesses/Closing.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../process.xsd"
>
    <process name="Closing">
        <states>
            <state name="ready for closing"/>
            <state name="closed"/>
        </states>

        <transitions>
            <transition happy="true" >
                <source>ready for closing</source>
                <target>closed</target>
                <event>close</event>
            </transition>
        </transitions>

        <events>
            <event name="close" onEnter="true"/>
        </events>
    </process>
</statemachine>

=== spryker/demoshop/config/Zed/oms/BraintreeSubProcesses/Authorization.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../process.xsd"
>
    <process name="Authorization">
        <states>
            <state name="ready for authorization"/>
            <state name="pre-authorization succeeded"/>
            <state name="authorization succeeded"/>
            <state name="invalid"/>
            <state name="authorization timed-out"/>
            <state name="re-authorization succeeded"/>
            <state name="re-authorization failed"/>
            <state name="revert succeeded"/>
        </states>

        <transitions>
            <!-- pre-authorization -->
            <transition happy="true" condition="Braintree/IsPreAuthorizationApproved">
                <source>ready for authorization</source>
                <target>pre-authorization succeeded</target>
                <event>pre-authorize payment</event>
            </transition>

            <transition>
                <source>ready for authorization</source>
                <target>invalid</target>
                <event>pre-authorize payment</event>
            </transition>

            <transition happy="true">
                <source>pre-authorization succeeded</source>
                <target>authorization succeeded</target>
                <event>authorize payment</event>
            </transition>

            <!-- re-authorization -->
            <transition happy="true" condition="Braintree/IsReAuthorizationApproved">
                <source>authorization succeeded</source>
                <target>re-authorization succeeded</target>
                <event>re-authorize payment</event>
            </transition>

            <transition>
                <source>authorization succeeded</source>
                <target>re-authorization failed</target>
                <event>re-authorize payment</event>
            </transition>

            <transition>
                <source>re-authorization succeeded</source>
                <target>authorization succeeded</target>
                <event>authorize payment</event>
            </transition>

            <transition>
                <source>re-authorization failed</source>
                <target>pre-authorization succeeded</target>
                <event>use previous pre-authorization</event>
            </transition>

            <!-- authorization timeout -->
            <transition>
                <source>authorization succeeded</source>
                <target>authorization timed-out</target>
                <event>timeout authorized payment</event>
            </transition>

            <transition happy="true" condition="Braintree/IsPreAuthorizationApproved">
                <source>authorization timed-out</source>
                <target>pre-authorization succeeded</target>
                <event>pre-authorize timed-out payment</event>
            </transition>

            <!-- reversal -->
            <transition happy="true" condition="Braintree/IsReversalApproved">
                <source>authorization succeeded</source>
                <target>revert succeeded</target>
                <event>revert payment</event>
            </transition>
        </transitions>

        <events>
            <event name="pre-authorize payment" onEnter="true" command="Braintree/PreAuthorize"/>
            <event name="re-authorize payment" manual="true" command="Braintree/ReAuthorize"/>
            <event name="authorize payment" onEnter="true"/>
            <event name="use previous pre-authorization" manual="true"/>
            <event name="timeout authorized payment" timeout="21days"/>
            <event name="pre-authorize timed-out payment" manual="true" command="Braintree/PreAuthorize"/>
            <event name="revert payment" manual="true" command="Braintree/Revert"/>
        </events>
    </process>
</statemachine>

=== spryker/demoshop/config/Zed/oms/BraintreeSubProcesses/Capture.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../process.xsd"
>
    <process name="Capture">
        <states>
            <state name="ready for capture"/>
            <state name="capture succeeded"/>
        </states>

        <transitions>
            <transition happy="true" condition="Braintree/IsCaptureApproved">
                <source>ready for capture</source>
                <target>capture succeeded</target>
                <event>capture payment</event>
            </transition>
        </transitions>

        <events>
            <event name="capture payment" onEnter="true" manual="true" command="Braintree/Capture"/>
        </events>
    </process>
</statemachine>
